Alcalyn\PayplugBundle\Model\Payment:
    extendEntity: Alcalyn\PayplugBundle\Model\Transaction
    type: mappedSuperclass
    fields:
        currency:
            type: string
            column: currency
            length: 7
            nullable: true
        ipnUrl:
            type: string
            column: ipn_url
            length: 255
            nullable: true
        returnUrl:
            type: string
            column: return_url
            length: 255
            nullable: true
        cancelUrl:
            type: string
            column: cancel_url
            length: 255
            nullable: true
