<?php

namespace Alcalyn\PayplugBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IPNRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IPNRepository extends EntityRepository
{
}
